# ============================================
# Cloud Build - CI/CD para GCP
# ============================================
# Alternativa ao GitHub Actions para build direto no GCP
# Trigger automático em push para main

steps:
  # ==========================================
  # Backend: Testes
  # ==========================================
  - id: 'backend-test'
    name: 'python:3.11-slim'
    entrypoint: 'bash'
    dir: 'backend'
    args:
      - '-c'
      - |
        pip install poetry
        poetry config virtualenvs.create false
        poetry install
        poetry run pytest --cov=app -v
    waitFor: ['-']

  # ==========================================
  # Frontend: Build
  # ==========================================
  - id: 'frontend-build'
    name: 'node:20-alpine'
    entrypoint: 'bash'
    dir: 'frontend'
    args:
      - '-c'
      - |
        npm ci
        npm run build
    waitFor: ['-']

  # ==========================================
  # Backend: Build Docker Image
  # ==========================================
  - id: 'backend-docker-build'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/crm-juridico-api:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/crm-juridico-api:latest'
      - './backend'
    waitFor: ['backend-test']

  # ==========================================
  # Frontend: Build Docker Image
  # ==========================================
  - id: 'frontend-docker-build'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/crm-juridico-frontend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/crm-juridico-frontend:latest'
      - './frontend'
    waitFor: ['frontend-build']

  # ==========================================
  # Push Images
  # ==========================================
  - id: 'push-backend'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/crm-juridico-api']
    waitFor: ['backend-docker-build']

  - id: 'push-frontend'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/crm-juridico-frontend']
    waitFor: ['frontend-docker-build']

  # ==========================================
  # Database Migration
  # ==========================================
  - id: 'db-migrate'
    name: 'gcr.io/$PROJECT_ID/crm-juridico-api:$SHORT_SHA'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /app
        alembic upgrade head
    env:
      - 'DATABASE_URL=$$DATABASE_URL'
    secretEnv: ['DATABASE_URL']
    waitFor: ['push-backend']

  # ==========================================
  # Deploy API to Cloud Run
  # ==========================================
  - id: 'deploy-api'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'crm-juridico-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/crm-juridico-api:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--vpc-connector'
      - 'crm-juridico-connector'
      - '--set-secrets'
      - 'SECRET_KEY=crm-juridico-jwt-secret:latest,GEMINI_API_KEY=crm-juridico-gemini-api-key:latest'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,ENVIRONMENT=production'
    waitFor: ['db-migrate']

  # ==========================================
  # Deploy Frontend to Cloud Run
  # ==========================================
  - id: 'deploy-frontend'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'crm-juridico-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/crm-juridico-frontend:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
    waitFor: ['push-frontend']

  # ==========================================
  # Deploy Worker to Cloud Run
  # ==========================================
  - id: 'deploy-worker'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'crm-juridico-worker'
      - '--image'
      - 'gcr.io/$PROJECT_ID/crm-juridico-api:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--vpc-connector'
      - 'crm-juridico-connector'
      - '--command'
      - 'celery,-A,app.workers.celery_app,worker,--loglevel=info'
      - '--set-secrets'
      - 'SECRET_KEY=crm-juridico-jwt-secret:latest,GEMINI_API_KEY=crm-juridico-gemini-api-key:latest'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,ENVIRONMENT=production'
      - '--no-cpu-throttling'
    waitFor: ['deploy-api']

# ==========================================
# Secrets from Secret Manager
# ==========================================
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/crm-juridico-db-url/versions/latest
      env: 'DATABASE_URL'

# ==========================================
# Substitutions (configurable)
# ==========================================
substitutions:
  _REGION: 'southamerica-east1'

# ==========================================
# Options
# ==========================================
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout
timeout: '1800s'

# Images to store in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/crm-juridico-api:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/crm-juridico-api:latest'
  - 'gcr.io/$PROJECT_ID/crm-juridico-frontend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/crm-juridico-frontend:latest'
